// Pure-Dart code generator that emits `lib/core/generated/assistant_turn_v1.dart`
// from the canonical spec 069 wire-schema artifact at
// `internal/assistant/schema/assistant_turn_v1.json`.
//
// Spec 073 Scope 1d: this generator is the single source of truth for the
// shared mobile core's wire models. The committed
// `lib/core/generated/assistant_turn_v1.dart` MUST be produced only by this
// generator. The drift test in `test/codegen_drift_test.dart` regenerates
// into a temporary directory and fails if the committed bytes diverge from
// the schema.

import 'dart:convert';

import 'package:dart_style/dart_style.dart';

/// Repository-root–relative path of the canonical wire-schema artifact.
const String schemaFile = 'internal/assistant/schema/assistant_turn_v1.json';

/// Repository-root–relative path of the committed generated Dart file.
const String generatedFile =
    'clients/mobile/assistant/lib/core/generated/assistant_turn_v1.dart';

/// Schema definitions in source order; iteration order is fixed so output
/// is deterministic regardless of map-iteration order.
const List<String> definitionOrder = <String>[
  'TurnRequest',
  'TurnResponse',
  'NoticePayload',
  'Source',
  'ConfirmCard',
  'Disambiguation',
  'DisambiguationChoice',
  'Trace',
];

const String _generatedHeader = '''
// GENERATED by clients/mobile/assistant/lib/src/codegen.dart from
// internal/assistant/schema/assistant_turn_v1.json (spec 069 v1).
// DO NOT EDIT — regenerate via:
//   cd clients/mobile/assistant && dart run tool/gen_dart_models.dart
//
// Spec 073 Scope 1d: this artifact is consumed by the shared mobile core
// in clients/mobile/assistant/lib/core/ and is pinned by the codegen-drift
// test in clients/mobile/assistant/test/codegen_drift_test.dart.
''';

class _Definition {
  _Definition(this.required, this.properties, this.optional);
  final List<String> required;
  final Map<String, Map<String, dynamic>> properties;
  /// Schema property names that are NOT in `required`. Treated as
  /// v1-compatible additive optional fields (spec 075 SCOPE-075-06.2b).
  final List<String> optional;
}

/// Generate the Dart source for `assistant_turn_v1.dart` from raw schema
/// bytes. Identical input bytes yield identical output bytes.
String generateAssistantTurnV1Dart(List<int> schemaBytes) {
  final dynamic decoded = jsonDecode(utf8.decode(schemaBytes));
  if (decoded is! Map<String, dynamic>) {
    throw FormatException('schema root is not a JSON object');
  }
  final String schemaVersion = _requireString(decoded, 'schema_version');
  final List<String> kindAllowlist =
      _requireStringList(decoded, 'kind_allowlist');
  final List<String> transportHintAllowlist =
      _requireStringList(decoded, 'transport_hint_allowlist');
  final Map<String, dynamic> rawDefs = _requireMap(decoded, 'definitions');

  final Map<String, _Definition> defs = <String, _Definition>{};
  for (final String name in definitionOrder) {
    final dynamic raw = rawDefs[name];
    if (raw is! Map<String, dynamic>) {
      throw FormatException('schema missing definition "$name"');
    }
    final List<String> required = _requireStringList(raw, 'required');
    if (required.isEmpty) {
      throw FormatException('definition "$name" has no required fields');
    }
    final Map<String, dynamic> properties = _requireMap(raw, 'properties');
    final Map<String, Map<String, dynamic>> typedProps =
        <String, Map<String, dynamic>>{};
    for (final String field in required) {
      final dynamic prop = properties[field];
      if (prop is! Map<String, dynamic>) {
        throw FormatException(
            'definition "$name" required field "$field" missing property entry');
      }
      typedProps[field] = prop;
    }
    final Set<String> requiredSet = required.toSet();
    final List<String> optional = <String>[];
    for (final String field in properties.keys) {
      if (requiredSet.contains(field)) continue;
      final dynamic prop = properties[field];
      if (prop is! Map<String, dynamic>) {
        throw FormatException(
            'definition "$name" optional field "$field" missing property entry');
      }
      typedProps[field] = prop;
      optional.add(field);
    }
    optional.sort();
    defs[name] = _Definition(required, typedProps, optional);
  }

  final List<String> extras = <String>[];
  for (final String name in rawDefs.keys) {
    if (!definitionOrder.contains(name)) extras.add(name);
  }
  if (extras.isNotEmpty) {
    extras.sort();
    throw FormatException(
        'schema has unknown definitions $extras — update definitionOrder in codegen.dart');
  }

  final StringBuffer b = StringBuffer();
  b.write(_generatedHeader);
  b.writeln();
  b.writeln('// ignore_for_file: constant_identifier_names');
  b.writeln();
  b.writeln(
      "const String assistantTurnSchemaVersion = ${_dartString(schemaVersion)};");
  b.writeln();
  b.writeln('const List<String> assistantTurnAllowedKinds = <String>[');
  for (final String v in kindAllowlist) {
    b.writeln('  ${_dartString(v)},');
  }
  b.writeln('];');
  b.writeln();
  b.writeln(
      'const List<String> assistantTurnAllowedTransportHints = <String>[');
  for (final String v in transportHintAllowlist) {
    b.writeln('  ${_dartString(v)},');
  }
  b.writeln('];');
  b.writeln();

  for (final String name in definitionOrder) {
    b.writeln('const List<String> ${_screamingSnake(name)}_FIELDS = <String>[');
    for (final String f in defs[name]!.required) {
      b.writeln('  ${_dartString(f)},');
    }
    b.writeln('];');
    b.writeln();
  }

  // Per-definition validator functions.
  for (final String name in definitionOrder) {
    final _Definition d = defs[name]!;
    final String fn = 'validate$name';
    b.writeln('Map<String, dynamic> $fn(Object? obj) {');
    b.writeln('  if (obj is! Map<String, dynamic>) {');
    b.writeln('    throw FormatException("$name: expected JSON object");');
    b.writeln('  }');
    b.writeln('  for (final String f in ${_screamingSnake(name)}_FIELDS) {');
    b.writeln('    if (!obj.containsKey(f)) {');
    b.writeln(
        '      throw FormatException("$name: missing required field \\\$f");');
    b.writeln('    }');
    b.writeln('  }');
    for (final String field in d.required) {
      b.write(_validatorLines(name, field, d.properties[field]!));
    }
    // Optional fields: only validate when present and non-null.
    // Additive v1-compatible (spec 075 SCOPE-075-06.2b).
    for (final String field in d.optional) {
      final String inner = _validatorLines(name, field, d.properties[field]!);
      b.writeln(
          '  if (obj.containsKey(${_dartString(field)}) && obj[${_dartString(field)}] != null) {');
      // Re-indent inner block (each line is `  ...`; we add two more
      // spaces so it sits inside the `if`).
      for (final String line in inner.split('\n')) {
        if (line.isEmpty) continue;
        b.writeln('  $line');
      }
      b.writeln('  }');
    }
    b.writeln('  return obj;');
    b.writeln('}');
    b.writeln();
  }

  final String raw = b.toString();
  final DartFormatter formatter = DartFormatter();
  return formatter.format(raw);
}

String _validatorLines(
    String defName, String field, Map<String, dynamic> prop) {
  if (field == 'schema_version') {
    return '  if (obj[${_dartString(field)}] != assistantTurnSchemaVersion) {\n'
        '    throw FormatException("$defName.$field: expected \\\$assistantTurnSchemaVersion, got \\\${obj[${_dartString(field)}]}");\n'
        '  }\n';
  }
  final List<String>? enumVals =
      (prop['enum'] is List) ? List<String>.from(prop['enum'] as List) : null;
  if (enumVals != null && enumVals.isNotEmpty) {
    final String listLit = enumVals.map(_dartString).join(', ');
    return '  if (obj[${_dartString(field)}] is! String) {\n'
        '    throw FormatException("$defName.$field: expected string");\n'
        '  }\n'
        '  if (!const <String>[$listLit].contains(obj[${_dartString(field)}])) {\n'
        '    throw FormatException("$defName.$field: value \\\${obj[${_dartString(field)}]} not in allowlist");\n'
        '  }\n';
  }
  if (prop.containsKey(r'const')) {
    final dynamic c = prop[r'const'];
    final String literal = c is String ? _dartString(c) : jsonEncode(c);
    return '  if (obj[${_dartString(field)}] != $literal) {\n'
        '    throw FormatException("$defName.$field: expected const $literal");\n'
        '  }\n';
  }
  final dynamic t = prop['type'];
  if (t is String) {
    switch (t) {
      case 'string':
        return '  if (obj[${_dartString(field)}] is! String) {\n'
            '    throw FormatException("$defName.$field: expected string");\n'
            '  }\n';
      case 'integer':
        return '  if (obj[${_dartString(field)}] is! int) {\n'
            '    throw FormatException("$defName.$field: expected integer");\n'
            '  }\n';
      case 'boolean':
        return '  if (obj[${_dartString(field)}] is! bool) {\n'
            '    throw FormatException("$defName.$field: expected boolean");\n'
            '  }\n';
      case 'object':
        return '  if (obj[${_dartString(field)}] is! Map<String, dynamic>) {\n'
            '    throw FormatException("$defName.$field: expected object");\n'
            '  }\n';
      case 'array':
        return '  if (obj[${_dartString(field)}] is! List) {\n'
            '    throw FormatException("$defName.$field: expected array");\n'
            '  }\n';
    }
  }
  if (prop[r'$ref'] is String) {
    final String nested = _refName(prop[r'$ref'] as String);
    return '  validate$nested(obj[${_dartString(field)}]);\n';
  }
  if (prop['oneOf'] is List) {
    String? refTarget;
    for (final dynamic o in prop['oneOf'] as List) {
      if (o is Map<String, dynamic> && o[r'$ref'] is String) {
        refTarget = _refName(o[r'$ref'] as String);
      }
    }
    if (refTarget != null) {
      return '  if (obj[${_dartString(field)}] != null) {\n'
          '    validate$refTarget(obj[${_dartString(field)}]);\n'
          '  }\n';
    }
  }
  throw FormatException(
      'unsupported property shape for $defName.$field: $prop');
}

String _refName(String ref) {
  const String prefix = '#/definitions/';
  if (!ref.startsWith(prefix)) {
    throw FormatException('unsupported \$ref: $ref');
  }
  return ref.substring(prefix.length);
}

String _dartString(String s) {
  final String escaped = s.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
  return "'$escaped'";
}

String _screamingSnake(String name) {
  final StringBuffer b = StringBuffer();
  for (int i = 0; i < name.length; i++) {
    final String c = name[i];
    if (i > 0 &&
        c.toUpperCase() == c &&
        name[i - 1].toLowerCase() == name[i - 1]) {
      b.write('_');
    }
    b.write(c.toUpperCase());
  }
  return b.toString();
}

String _requireString(Map<String, dynamic> m, String k) {
  final dynamic v = m[k];
  if (v is! String || v.isEmpty) {
    throw FormatException('missing or empty string field "$k"');
  }
  return v;
}

List<String> _requireStringList(Map<String, dynamic> m, String k) {
  final dynamic v = m[k];
  if (v is! List) {
    throw FormatException('missing list field "$k"');
  }
  return v.map((dynamic e) {
    if (e is! String) {
      throw FormatException('field "$k" contains non-string element');
    }
    return e;
  }).toList(growable: false);
}

Map<String, dynamic> _requireMap(Map<String, dynamic> m, String k) {
  final dynamic v = m[k];
  if (v is! Map<String, dynamic>) {
    throw FormatException('missing map field "$k"');
  }
  return v;
}
