// TP-073-01 — codegen drift test (spec 073 Scope 1d).
//
// Regenerates the committed Dart wire-schema artifact into a temporary
// directory and fails if the committed file diverges from the schema. This
// is the single guard that prevents the shared mobile core from carrying
// stale models after the spec 069 canonical schema changes.

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:smackerel_assistant/src/codegen.dart';

File _findRepoRoot() {
  Directory cur = Directory.current.absolute;
  while (true) {
    if (Directory('${cur.path}/.git').existsSync() ||
        File('${cur.path}/go.mod').existsSync()) {
      return File(cur.path);
    }
    final Directory parent = cur.parent;
    if (parent.path == cur.path) {
      fail('could not locate repo root from ${Directory.current.path}');
    }
    cur = parent;
  }
}

void main() {
  group('TP-073-01 — Dart wire-schema codegen drift', () {
    test('committed artifact matches regenerated bytes', () {
      final String root = _findRepoRoot().path;
      final File schema = File('$root/$schemaFile');
      expect(schema.existsSync(), isTrue,
          reason: 'schema artifact missing at ${schema.path}');
      final String regenerated =
          generateAssistantTurnV1Dart(schema.readAsBytesSync());
      final File committed = File('$root/$generatedFile');
      expect(committed.existsSync(), isTrue,
          reason: 'generated artifact missing at ${committed.path}');
      final String onDisk = committed.readAsStringSync();
      expect(onDisk, equals(regenerated),
          reason:
              'committed ${committed.path} diverges from regenerated output; '
              'run `dart run tool/gen_dart_models.dart` to refresh.');
    });

    test('regeneration is deterministic across runs', () {
      final String root = _findRepoRoot().path;
      final List<int> schemaBytes = File('$root/$schemaFile').readAsBytesSync();
      final String a = generateAssistantTurnV1Dart(schemaBytes);
      final String b = generateAssistantTurnV1Dart(schemaBytes);
      expect(a, equals(b));
    });

    test('adversarial drift fails the comparison', () {
      // Adversarial RED: simulate a schema artifact whose committed Dart
      // output has been hand-edited away from the canonical schema. The
      // drift comparator MUST flag the divergence — proving this test
      // would catch a regression where the committed file falls out of
      // sync with the schema.
      final String root = _findRepoRoot().path;
      final List<int> schemaBytes = File('$root/$schemaFile').readAsBytesSync();
      final String regenerated = generateAssistantTurnV1Dart(schemaBytes);
      final String tampered = regenerated.replaceFirst(
          "assistantTurnSchemaVersion = 'v1'",
          "assistantTurnSchemaVersion = 'v2-tampered'");
      expect(tampered == regenerated, isFalse,
          reason: 'tampered string should differ from canonical regeneration');
    });
  });
}
