// Package webcodegen emits the web/PWA JavaScript + TypeScript
// declaration artifacts that mirror the canonical assistant-turn v1
// wire schema (spec 069) for spec 073 Scope 1c.
//
// The generator is the single source of truth for the web client's
// model fields and runtime validator. Files in web/pwa/generated/
// MUST only be produced by this package — never hand-edited — and
// MUST be regenerated whenever
// internal/assistant/schema/assistant_turn_v1.json changes. The
// codegen-drift test in web/pwa/tests/ regenerates into a temporary
// directory and fails if the committed artifacts diverge from the
// schema.
package webcodegen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// SchemaFile is the canonical wire-schema path (relative to repo
// root) that this generator consumes.
const SchemaFile = "internal/assistant/schema/assistant_turn_v1.json"

// GeneratedDir is the committed output directory (relative to repo
// root) for the web/PWA generated artifacts.
const GeneratedDir = "web/pwa/generated"

// JSFile and DTSFile are the artifact basenames the generator emits.
const (
	JSFile  = "assistant_turn_v1.js"
	DTSFile = "assistant_turn_v1.d.ts"
)

// generatedHeader is prepended to every emitted artifact so that any
// hand-edit is obviously wrong and the regeneration command is
// always one grep away.
const generatedHeader = `// Code generated by cmd/web-assistant-codegen from
// internal/assistant/schema/assistant_turn_v1.json (spec 069 v1).
// DO NOT EDIT — regenerate via:
//   ./smackerel.sh build
// or directly:
//   go run ./cmd/web-assistant-codegen
//
// Spec 073 Scope 1c: this artifact is consumed by web/pwa/assistant*.js.
`

type schemaDoc struct {
	SchemaVersion          string                     `json:"schema_version"`
	TransportHintAllowlist []string                   `json:"transport_hint_allowlist"`
	KindAllowlist          []string                   `json:"kind_allowlist"`
	Definitions            map[string]json.RawMessage `json:"definitions"`
}

type definition struct {
	Required   []string                   `json:"required"`
	Properties map[string]json.RawMessage `json:"properties"`
	// optional is the schema property names that are present in
	// Properties but absent from Required. Populated by Generate
	// (not unmarshalled from JSON). v1-compatible additive optional
	// fields (spec 075 SCOPE-075-06.2b).
	optional []string
}

// definitionOrder lists the schema definitions in the order they
// appear in assistant_turn_v1.json. The generator iterates this list
// rather than ranging the definitions map so output is deterministic
// across Go map-iteration orders.
var definitionOrder = []string{
	"TurnRequest",
	"TurnResponse",
	"NoticePayload",
	"Source",
	"ConfirmCard",
	"Disambiguation",
	"DisambiguationChoice",
	"Trace",
}

// Artifacts is the map of artifact basename → bytes that Generate
// returns. Callers (the codegen CLI and the drift test) compare or
// write these to disk.
type Artifacts map[string][]byte

// Generate parses the canonical wire-schema JSON and emits the
// committed web/PWA artifacts. The output is deterministic: identical
// input bytes produce identical output bytes.
func Generate(schemaBytes []byte) (Artifacts, error) {
	var doc schemaDoc
	dec := json.NewDecoder(bytes.NewReader(schemaBytes))
	dec.DisallowUnknownFields()
	// Top-level JSON Schema fields we ignore are unknown to dec; use
	// a permissive decoder instead.
	dec = json.NewDecoder(bytes.NewReader(schemaBytes))
	if err := dec.Decode(&doc); err != nil {
		return nil, fmt.Errorf("decode schema: %w", err)
	}
	if doc.SchemaVersion == "" {
		return nil, fmt.Errorf("schema missing top-level schema_version")
	}
	if len(doc.KindAllowlist) == 0 {
		return nil, fmt.Errorf("schema missing kind_allowlist")
	}
	if len(doc.TransportHintAllowlist) == 0 {
		return nil, fmt.Errorf("schema missing transport_hint_allowlist")
	}
	defs := make(map[string]definition, len(doc.Definitions))
	for _, name := range definitionOrder {
		raw, ok := doc.Definitions[name]
		if !ok {
			return nil, fmt.Errorf("schema missing definition %q", name)
		}
		var d definition
		if err := json.Unmarshal(raw, &d); err != nil {
			return nil, fmt.Errorf("decode definition %q: %w", name, err)
		}
		if len(d.Required) == 0 {
			return nil, fmt.Errorf("definition %q has no required fields", name)
		}
		for _, fieldName := range d.Required {
			if _, present := d.Properties[fieldName]; !present {
				return nil, fmt.Errorf("definition %q required field %q has no property entry", name, fieldName)
			}
		}
		// Collect OPTIONAL fields (in Properties but not in Required)
		// in deterministic order.
		reqSet := make(map[string]bool, len(d.Required))
		for _, r := range d.Required {
			reqSet[r] = true
		}
		var opt []string
		for fieldName := range d.Properties {
			if !reqSet[fieldName] {
				opt = append(opt, fieldName)
			}
		}
		sort.Strings(opt)
		d.optional = opt
		defs[name] = d
	}
	// Surface any extra definitions so a schema addition is caught.
	if len(doc.Definitions) != len(definitionOrder) {
		extras := make([]string, 0)
		for name := range doc.Definitions {
			found := false
			for _, known := range definitionOrder {
				if known == name {
					found = true
					break
				}
			}
			if !found {
				extras = append(extras, name)
			}
		}
		sort.Strings(extras)
		return nil, fmt.Errorf("schema has unknown definitions %v — update webcodegen.definitionOrder", extras)
	}

	js, err := renderJS(doc, defs)
	if err != nil {
		return nil, fmt.Errorf("render js: %w", err)
	}
	dts, err := renderDTS(doc, defs)
	if err != nil {
		return nil, fmt.Errorf("render dts: %w", err)
	}
	return Artifacts{
		JSFile:  js,
		DTSFile: dts,
	}, nil
}

func renderJS(doc schemaDoc, defs map[string]definition) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(generatedHeader)
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("export const SCHEMA_VERSION = %s;\n", jsString(doc.SchemaVersion)))
	b.WriteString(fmt.Sprintf("export const ALLOWED_KINDS = Object.freeze(%s);\n", jsStringArray(doc.KindAllowlist)))
	b.WriteString(fmt.Sprintf("export const ALLOWED_TRANSPORT_HINTS = Object.freeze(%s);\n\n", jsStringArray(doc.TransportHintAllowlist)))

	for _, name := range definitionOrder {
		d := defs[name]
		b.WriteString(fmt.Sprintf("export const %s_FIELDS = Object.freeze(%s);\n", screamingSnake(name), jsStringArray(d.Required)))
	}
	b.WriteString("\n")

	b.WriteString(`function requireObject(obj, label) {
  if (obj === null || typeof obj !== "object" || Array.isArray(obj)) {
    throw new TypeError(label + ": expected object");
  }
}

function requireFields(obj, label, fields) {
  for (const f of fields) {
    if (!Object.prototype.hasOwnProperty.call(obj, f)) {
      throw new TypeError(label + ": missing required field '" + f + "'");
    }
  }
}

function requireString(obj, label, field) {
  if (typeof obj[field] !== "string") {
    throw new TypeError(label + "." + field + ": expected string");
  }
}

function requireInteger(obj, label, field) {
  const v = obj[field];
  if (typeof v !== "number" || !Number.isInteger(v)) {
    throw new TypeError(label + "." + field + ": expected integer");
  }
}

function requireBoolean(obj, label, field) {
  if (typeof obj[field] !== "boolean") {
    throw new TypeError(label + "." + field + ": expected boolean");
  }
}

function requireArray(obj, label, field) {
  if (!Array.isArray(obj[field])) {
    throw new TypeError(label + "." + field + ": expected array");
  }
}

function requireEnum(obj, label, field, allowed) {
  if (!allowed.includes(obj[field])) {
    throw new TypeError(label + "." + field + ": value '" + String(obj[field]) + "' not in allowlist " + JSON.stringify(allowed));
  }
}

function requireSchemaVersion(obj, label) {
  if (obj.schema_version !== SCHEMA_VERSION) {
    throw new TypeError(label + ".schema_version: expected '" + SCHEMA_VERSION + "', got '" + String(obj.schema_version) + "'");
  }
}

`)

	// Per-definition validator
	for _, name := range definitionOrder {
		d := defs[name]
		fnName := "validate" + name
		b.WriteString(fmt.Sprintf("export function %s(obj) {\n", fnName))
		b.WriteString(fmt.Sprintf("  requireObject(obj, %s);\n", jsString(name)))
		b.WriteString(fmt.Sprintf("  requireFields(obj, %s, %s_FIELDS);\n", jsString(name), screamingSnake(name)))
		for _, field := range d.Required {
			raw := d.Properties[field]
			line, err := validatorLine(name, field, raw)
			if err != nil {
				return nil, err
			}
			b.WriteString(line)
		}
		// Optional fields: only validate when the property is present
		// on the wire object (additive v1-compatible — absence is OK).
		for _, field := range d.optional {
			raw := d.Properties[field]
			line, err := validatorLine(name, field, raw)
			if err != nil {
				return nil, err
			}
			b.WriteString(fmt.Sprintf("  if (Object.prototype.hasOwnProperty.call(obj, %s) && obj[%s] !== null && obj[%s] !== undefined) {\n", jsString(field), jsString(field), jsString(field)))
			// Indent the inner validation line by an extra two spaces.
			b.WriteString("  " + line)
			b.WriteString("  }\n")
		}
		b.WriteString("  return obj;\n")
		b.WriteString("}\n\n")
	}

	return b.Bytes(), nil
}

func validatorLine(defName, field string, raw json.RawMessage) (string, error) {
	var probe struct {
		Type  string          `json:"type"`
		Enum  []string        `json:"enum"`
		Const json.RawMessage `json:"const"`
		OneOf []struct {
			Type string `json:"type"`
			Ref  string `json:"$ref"`
		} `json:"oneOf"`
		Items struct {
			Ref string `json:"$ref"`
		} `json:"items"`
		Ref string `json:"$ref"`
	}
	if err := json.Unmarshal(raw, &probe); err != nil {
		return "", fmt.Errorf("decode property %s.%s: %w", defName, field, err)
	}
	label := jsString(defName)
	fieldLit := jsString(field)
	// schema_version uses the SCHEMA_VERSION constant.
	if field == "schema_version" {
		return fmt.Sprintf("  requireSchemaVersion(obj, %s);\n", label), nil
	}
	if len(probe.Enum) > 0 {
		return fmt.Sprintf("  requireString(obj, %s, %s);\n  requireEnum(obj, %s, %s, %s);\n",
			label, fieldLit, label, fieldLit, jsStringArray(probe.Enum)), nil
	}
	if len(probe.Const) > 0 {
		// Const literal — emit equality check.
		return fmt.Sprintf("  if (JSON.stringify(obj[%s]) !== %s) { throw new TypeError(%s + \".%s: expected const \" + %s); }\n",
			fieldLit, jsString(string(probe.Const)), label, field, jsString(string(probe.Const))), nil
	}
	switch probe.Type {
	case "string":
		return fmt.Sprintf("  requireString(obj, %s, %s);\n", label, fieldLit), nil
	case "integer":
		return fmt.Sprintf("  requireInteger(obj, %s, %s);\n", label, fieldLit), nil
	case "boolean":
		return fmt.Sprintf("  requireBoolean(obj, %s, %s);\n", label, fieldLit), nil
	case "object":
		// Bare object (e.g., client_context) — only require object shape.
		return fmt.Sprintf("  requireObject(obj[%s], %s + \".%s\");\n", fieldLit, label, field), nil
	case "array":
		return fmt.Sprintf("  requireArray(obj, %s, %s);\n", label, fieldLit), nil
	}
	if probe.Ref != "" {
		nested := refName(probe.Ref)
		return fmt.Sprintf("  validate%s(obj[%s]);\n", nested, fieldLit), nil
	}
	if len(probe.OneOf) > 0 {
		// Nullable nested object: oneOf [null, $ref].
		var refTarget string
		for _, o := range probe.OneOf {
			if o.Ref != "" {
				refTarget = refName(o.Ref)
			}
		}
		hasNull := false
		for _, o := range probe.OneOf {
			if o.Type == "null" {
				hasNull = true
			}
		}
		if refTarget != "" && hasNull {
			return fmt.Sprintf("  if (obj[%s] !== null) { validate%s(obj[%s]); }\n", fieldLit, refTarget, fieldLit), nil
		}
	}
	return "", fmt.Errorf("property %s.%s has unsupported shape; update webcodegen.validatorLine: %s", defName, field, string(raw))
}

func renderDTS(doc schemaDoc, defs map[string]definition) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(generatedHeader)
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("export const SCHEMA_VERSION: %s;\n", jsString(doc.SchemaVersion)))
	b.WriteString(fmt.Sprintf("export const ALLOWED_KINDS: readonly %s[];\n", unionLiteral(doc.KindAllowlist)))
	b.WriteString(fmt.Sprintf("export const ALLOWED_TRANSPORT_HINTS: readonly %s[];\n\n", unionLiteral(doc.TransportHintAllowlist)))

	for _, name := range definitionOrder {
		d := defs[name]
		b.WriteString(fmt.Sprintf("export const %s_FIELDS: readonly string[];\n", screamingSnake(name)))
		b.WriteString(fmt.Sprintf("export interface %s {\n", name))
		for _, field := range d.Required {
			tsType, err := dtsType(d.Properties[field], doc)
			if err != nil {
				return nil, fmt.Errorf("%s.%s: %w", name, field, err)
			}
			b.WriteString(fmt.Sprintf("  %s: %s;\n", field, tsType))
		}
		// Optional fields: emit with `?:` so existing clients
		// continue to type-check while regenerated clients see
		// the typed optional field.
		for _, field := range d.optional {
			tsType, err := dtsType(d.Properties[field], doc)
			if err != nil {
				return nil, fmt.Errorf("%s.%s (optional): %w", name, field, err)
			}
			b.WriteString(fmt.Sprintf("  %s?: %s;\n", field, tsType))
		}
		b.WriteString("}\n")
		b.WriteString(fmt.Sprintf("export function validate%s(obj: unknown): %s;\n\n", name, name))
	}

	return b.Bytes(), nil
}

func dtsType(raw json.RawMessage, doc schemaDoc) (string, error) {
	var probe struct {
		Type  string          `json:"type"`
		Enum  []string        `json:"enum"`
		Const json.RawMessage `json:"const"`
		OneOf []struct {
			Type string `json:"type"`
			Ref  string `json:"$ref"`
		} `json:"oneOf"`
		Items struct {
			Ref string `json:"$ref"`
		} `json:"items"`
		Ref string `json:"$ref"`
	}
	if err := json.Unmarshal(raw, &probe); err != nil {
		return "", err
	}
	if len(probe.Const) > 0 {
		return strings.TrimSpace(string(probe.Const)), nil
	}
	if len(probe.Enum) > 0 {
		return unionLiteral(probe.Enum), nil
	}
	switch probe.Type {
	case "string":
		return "string", nil
	case "integer":
		return "number", nil
	case "boolean":
		return "boolean", nil
	case "object":
		return "Record<string, unknown>", nil
	case "array":
		if probe.Items.Ref != "" {
			return refName(probe.Items.Ref) + "[]", nil
		}
		return "unknown[]", nil
	}
	if probe.Ref != "" {
		return refName(probe.Ref), nil
	}
	if len(probe.OneOf) > 0 {
		var refTarget string
		hasNull := false
		for _, o := range probe.OneOf {
			if o.Ref != "" {
				refTarget = refName(o.Ref)
			}
			if o.Type == "null" {
				hasNull = true
			}
		}
		if refTarget != "" && hasNull {
			return refTarget + " | null", nil
		}
	}
	return "", fmt.Errorf("unsupported property shape: %s", string(raw))
}

func refName(ref string) string {
	const prefix = "#/definitions/"
	if strings.HasPrefix(ref, prefix) {
		return ref[len(prefix):]
	}
	return ref
}

func jsString(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}

func jsStringArray(values []string) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = jsString(v)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func unionLiteral(values []string) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = jsString(v)
	}
	return "(" + strings.Join(parts, " | ") + ")"
}

func screamingSnake(camel string) string {
	var b strings.Builder
	for i, r := range camel {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('_')
		}
		if r >= 'a' && r <= 'z' {
			b.WriteRune(r - 32)
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}
