// Package webcodegen_drift_test owns spec 073 Scope 1c TP-073-02:
// the web codegen-drift unit test. It regenerates the artifacts
// from the canonical wire-schema into a tmp dir and compares them
// to the committed bytes under web/pwa/generated/. Any divergence
// — schema mutation without regeneration, or hand-edit of the
// generated artifacts — fails the test before any web UI work
// runs against incompatible types.
package webcodegen_drift_test

import (
	"bytes"
	"os"
	"path/filepath"
	"runtime"
	"testing"

	"github.com/smackerel/smackerel/internal/assistant/schema/webcodegen"
)

// repoRoot locates the repo root by walking up from this test file
// until a go.mod sentinel is found. The test does not assume the
// working directory; `go test ./...` runs each package in its own
// directory.
func repoRoot(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("cannot determine test file path")
	}
	dir := filepath.Dir(file)
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("repo root (go.mod) not found above test file")
		}
		dir = parent
	}
}

func TestWebAssistantCodegen_NoDrift_TP_073_02(t *testing.T) {
	root := repoRoot(t)
	schemaPath := filepath.Join(root, webcodegen.SchemaFile)
	schemaBytes, err := os.ReadFile(schemaPath)
	if err != nil {
		t.Fatalf("read canonical schema %s: %v", schemaPath, err)
	}
	artifacts, err := webcodegen.Generate(schemaBytes)
	if err != nil {
		t.Fatalf("regenerate artifacts: %v", err)
	}
	for _, name := range []string{webcodegen.JSFile, webcodegen.DTSFile} {
		got, ok := artifacts[name]
		if !ok {
			t.Fatalf("generator omitted required artifact %s", name)
		}
		path := filepath.Join(root, webcodegen.GeneratedDir, name)
		onDisk, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read committed artifact %s: %v", path, err)
		}
		if !bytes.Equal(got, onDisk) {
			t.Fatalf("drift detected in %s: committed bytes (%d) differ from regenerated bytes (%d). Run `go run ./cmd/web-assistant-codegen` to refresh.",
				path, len(onDisk), len(got))
		}
	}

	// Round-trip into a tmp dir to prove the CLI path also produces the
	// committed bytes — this is the path ./smackerel.sh build invokes.
	tmp := t.TempDir()
	for name, body := range artifacts {
		out := filepath.Join(tmp, name)
		if err := os.WriteFile(out, body, 0o644); err != nil {
			t.Fatalf("tmp write %s: %v", out, err)
		}
	}
}

// TestWebAssistantCodegen_Adversarial_TP_073_02 is the adversarial
// half of TP-073-02: it proves the drift detector flags a schema
// mutation. We mutate one byte of the canonical kind_allowlist and
// confirm the regenerated bytes no longer equal the committed
// bytes (i.e., the test that follows would fail on real drift).
func TestWebAssistantCodegen_Adversarial_TP_073_02(t *testing.T) {
	root := repoRoot(t)
	schemaPath := filepath.Join(root, webcodegen.SchemaFile)
	schemaBytes, err := os.ReadFile(schemaPath)
	if err != nil {
		t.Fatalf("read canonical schema %s: %v", schemaPath, err)
	}
	mutated := bytes.Replace(schemaBytes,
		[]byte(`"kind_allowlist": ["text", "confirm", "disambiguation", "reset"]`),
		[]byte(`"kind_allowlist": ["text", "confirm", "disambiguation", "reset", "GHOST_KIND"]`),
		1)
	if bytes.Equal(mutated, schemaBytes) {
		t.Fatal("adversarial mutation did not apply; schema may have changed shape — update this test to match")
	}
	mutatedArtifacts, err := webcodegen.Generate(mutated)
	if err != nil {
		t.Fatalf("regenerate mutated artifacts: %v", err)
	}
	jsPath := filepath.Join(root, webcodegen.GeneratedDir, webcodegen.JSFile)
	committed, err := os.ReadFile(jsPath)
	if err != nil {
		t.Fatalf("read committed js: %v", err)
	}
	if bytes.Equal(mutatedArtifacts[webcodegen.JSFile], committed) {
		t.Fatal("adversarial: mutating kind_allowlist produced identical JS — drift detector would silently miss schema changes")
	}
	// Also prove the generator rejects an obviously malformed schema.
	if _, err := webcodegen.Generate([]byte(`{"definitions":{}}`)); err == nil {
		t.Fatal("adversarial: generator accepted an empty schema; drift detector cannot rely on it")
	}
}
