package intelligence

// vendorSeeds contains pre-seeded vendor alias mappings.
// Loaded at startup to populate the vendor_aliases table with source="system".
// These represent common merchant abbreviations found on credit card statements.
var vendorSeeds = []struct {
	Alias     string
	Canonical string
}{
	{"AMZN MKTP US", "Amazon"},
	{"AMZN MKTP", "Amazon"},
	{"AMAZON MARKETPLACE", "Amazon"},
	{"AMAZON.COM", "Amazon"},
	{"AMZN DIGITAL", "Amazon Digital"},
	{"APPLE.COM/BILL", "Apple"},
	{"APPLE.COM", "Apple"},
	{"GOOGLE *", "Google"},
	{"GOOGLE PLAY", "Google Play"},
	{"PAYPAL *", "PayPal"},
	{"SQ *", "Square"},
	{"UBER EATS", "Uber Eats"},
	{"UBER *TRIP", "Uber"},
	{"UBER *", "Uber"},
	{"LYFT *", "Lyft"},
	{"DOORDASH", "DoorDash"},
	{"GRUBHUB", "Grubhub"},
	{"NETFLIX.COM", "Netflix"},
	{"NETFLIX", "Netflix"},
	{"SPOTIFY USA", "Spotify"},
	{"SPOTIFY", "Spotify"},
	{"HULU", "Hulu"},
	{"DISNEY PLUS", "Disney+"},
	{"DROPBOX", "Dropbox"},
	{"ZOOM.US", "Zoom"},
	{"ZOOM VIDEO", "Zoom"},
	{"SLACK TECHNOLOGIES", "Slack"},
	{"GITHUB", "GitHub"},
	{"DIGITAL OCEAN", "DigitalOcean"},
	{"DIGITALOCEAN", "DigitalOcean"},
	{"AWS", "Amazon Web Services"},
	{"COSTCO WHSE", "Costco"},
	{"COSTCO", "Costco"},
	{"WALMART", "Walmart"},
	{"WM SUPERCENTER", "Walmart"},
	{"TARGET", "Target"},
	{"STARBUCKS", "Starbucks"},
	{"SHELL OIL", "Shell"},
	{"SHELL SERVICE", "Shell"},
	{"CHEVRON", "Chevron"},
	{"EXXONMOBIL", "ExxonMobil"},
	{"HOME DEPOT", "Home Depot"},
	{"LOWES", "Lowe's"},
	{"OFFICE DEPOT", "Office Depot"},
	{"STAPLES", "Staples"},
	{"BEST BUY", "Best Buy"},
	{"BESTBUY.COM", "Best Buy"},
	{"WALGREENS", "Walgreens"},
	{"CVS/PHARMACY", "CVS"},
}
