// report.go — spec 075 SCOPE-3 rolling residual-usage report types.
//
// The rolling 7-day report is the operator-facing answer to
// SCN-075-A04: per-command, per-day invocation counts plus distinct
// HMAC user-bucket totals over the trailing 7-day window. The report
// is a read-only projection of the assistant_legacy_retirement_residual
// table; it never mutates state and never returns raw user
// identifiers.
package legacyretirement

import (
	"context"
	"time"
)

// ResidualPerDayRow is a single (command, day) cell of the rolling
// report.
type ResidualPerDayRow struct {
	Command       string
	Day           time.Time // UTC midnight of the bucket day
	Invocations   int64
	DistinctUsers int64
}

// ResidualPerCommandRow is the per-command summary over the rolling
// window: total invocations and distinct HMAC user buckets observed.
type ResidualPerCommandRow struct {
	Command       string
	Invocations   int64
	DistinctUsers int64
}

// ResidualReport is the structured payload the dashboard panel and
// the CLI/admin diagnostic both render. Generated by
// ResidualReportQuery.RollingSevenDay.
type ResidualReport struct {
	WindowID   string
	StartDay   time.Time // UTC midnight, inclusive
	EndDay     time.Time // UTC midnight, inclusive (== now's date)
	PerDay     []ResidualPerDayRow
	PerCommand []ResidualPerCommandRow
}

// ResidualReportQuery is the seam the SQL residual store implements
// and the admin/CLI diagnostic consumes. Declaring it as an
// interface keeps the admin surface decoupled from the store
// implementation and unit-testable.
type ResidualReportQuery interface {
	// RollingSevenDay returns the trailing 7-day residual usage
	// report for windowID, anchored at now (UTC date). The returned
	// report contains exactly the days in [now-6, now], with absent
	// days omitted (the renderer fills zeros).
	RollingSevenDay(ctx context.Context, windowID string, now time.Time) (ResidualReport, error)
}
