#!/usr/bin/env bash
# agent-roster-coverage.sh
#
# Ensures every framework agent (agents/bubbles.*.agent.md) is documented on the
# hand-maintained roster surfaces. Those surfaces are NOT regenerated by
# generate-cheatsheet.sh (only the alias/mode/vocabulary BLOCKS are), so an
# agent can ship without a roster entry and no existing drift check catches it —
# exactly how bubbles.journey shipped present in the markdown cheatsheet yet
# absent from the HTML cheatsheet agent cards, README roster, and Agent Manual.
#
# Roster surfaces checked (source-repo layout):
#   - README.md                            (agent roster tables)
#   - docs/guides/AGENT_MANUAL.md          (situation -> agent tables)
#   - docs/its-not-rocket-appliances.html  (visual agent cards)
#
# An agent is "covered" on a surface when its name token appears there. Token
# matching (fixed-string, not exact-cell) tolerates combined entries such as
# "bubbles.handoff / bubbles.setup". Agent names are mutually non-substring, so
# a fixed-string match cannot produce a false pass.
#
# Exit 0 when every agent is covered on every surface, 1 when any gap exists,
# 2 on a usage/precondition error. There is no bypass flag.
#
# Usage:
#   bash bubbles/scripts/agent-roster-coverage.sh [--repo-root <path>]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT_DEFAULT="$(cd "$SCRIPT_DIR/../.." && pwd)"
repo_root="$REPO_ROOT_DEFAULT"

usage() {
  cat <<'EOF'
Usage: bash bubbles/scripts/agent-roster-coverage.sh [--repo-root <path>]

Verifies every agents/bubbles.*.agent.md appears in README.md,
docs/guides/AGENT_MANUAL.md, and docs/its-not-rocket-appliances.html.
Exits 0 when fully covered, 1 when any roster gap exists.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo-root)
      shift
      repo_root="${1:?--repo-root requires a path}"
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      echo "agent-roster-coverage: unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ ! -d "$repo_root/agents" ]]; then
  echo "agent-roster-coverage: agents/ not found under $repo_root" >&2
  exit 2
fi

declare -a surfaces=(
  "README.md"
  "docs/guides/AGENT_MANUAL.md"
  "docs/its-not-rocket-appliances.html"
)

for surface in "${surfaces[@]}"; do
  if [[ ! -f "$repo_root/$surface" ]]; then
    echo "agent-roster-coverage: roster surface missing: $surface" >&2
    exit 2
  fi
done

gaps=0
scanned=0
for agent_file in "$repo_root"/agents/bubbles.*.agent.md; do
  [[ -f "$agent_file" ]] || continue
  agent="$(basename "$agent_file" .agent.md)"
  scanned=$((scanned + 1))
  for surface in "${surfaces[@]}"; do
    if ! grep -qF "$agent" "$repo_root/$surface"; then
      echo "ROSTER_GAP: $agent missing from $surface"
      gaps=$((gaps + 1))
    fi
  done
done

echo "agent-roster-coverage: scanned $scanned agent(s) across ${#surfaces[@]} surface(s)"
if [[ "$gaps" -gt 0 ]]; then
  echo "agent-roster-coverage: FAIL — $gaps roster gap(s) detected" >&2
  echo "Action: add each agent above to the roster table/card on the named surface." >&2
  exit 1
fi
echo "agent-roster-coverage: OK — every agent is documented on every roster surface"
exit 0
