#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/trust-metadata.sh"

if [[ "$SCRIPT_DIR" == *"/.github/bubbles/scripts" ]]; then
  PROJECT_ROOT="${SCRIPT_DIR%/.github/bubbles/scripts}"
  FRAMEWORK_ROOT="$PROJECT_ROOT/.github/bubbles"
  MANAGED_ROOT="$PROJECT_ROOT/.github"
  SOURCE_REPO="false"
else
  PROJECT_ROOT="${SCRIPT_DIR%/bubbles/scripts}"
  FRAMEWORK_ROOT="$PROJECT_ROOT/bubbles"
  MANAGED_ROOT="$PROJECT_ROOT"
  SOURCE_REPO="true"
fi

CHECKSUM_FILE="$FRAMEWORK_ROOT/.checksums"
RELEASE_MANIFEST_FILE="$FRAMEWORK_ROOT/release-manifest.json"
INSTALL_PROVENANCE_FILE="$FRAMEWORK_ROOT/.install-source.json"
quiet="false"
violations=0
warnings=0
manifest_managed_count=''

usage() {
  cat <<'EOF'
Usage: bash .github/bubbles/scripts/downstream-framework-write-guard.sh [--quiet]

Checks that downstream framework-managed Bubbles files still match the last
upstream install/refresh checksum snapshot.

The Bubbles source repo is exempt because it is the framework authority.
EOF
}

info() {
  [[ "$quiet" == "true" ]] && return 0
  echo "ℹ️  $1"
}

pass() {
  [[ "$quiet" == "true" ]] && return 0
  echo "✅ $1"
}

fail_line() {
  echo "❌ $1"
  violations=$((violations + 1))
}

warn_line() {
  [[ "$quiet" == "true" ]] && return 0
  echo "⚠️  $1"
  warnings=$((warnings + 1))
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --quiet)
      quiet="true"
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ "$SOURCE_REPO" == "true" ]]; then
  pass "Bubbles source repo detected — downstream framework write guard is not applicable here"
  exit 0
fi

if [[ ! -f "$CHECKSUM_FILE" ]]; then
  fail_line "Missing framework checksum snapshot: .github/bubbles/.checksums"
  [[ "$quiet" == "true" ]] || {
    echo "   Remediation: rerun the Bubbles installer or /bubbles.setup mode: refresh from the upstream Bubbles repo."
    echo "   Do not create or patch framework-managed files by hand in a consumer repo."
  }
  exit 1
fi

if [[ ! -f "$RELEASE_MANIFEST_FILE" ]]; then
  fail_line "Missing installed release manifest: .github/bubbles/release-manifest.json"
  [[ "$quiet" == "true" ]] || {
    echo "   Remediation: rerun the Bubbles installer or upgrade from the upstream Bubbles repo."
    echo "   Release trust metadata is generated by the source repo during release hygiene; do not author it by hand downstream."
  }
  exit 1
fi

if [[ ! -f "$INSTALL_PROVENANCE_FILE" ]]; then
  fail_line "Missing install provenance record: .github/bubbles/.install-source.json"
  [[ "$quiet" == "true" ]] || {
    echo "   Remediation: rerun the Bubbles installer or upgrade from the upstream Bubbles repo."
    echo "   Downstream trust checks require explicit install provenance and must not be repaired manually."
  }
  exit 1
fi

bubbles_validate_release_manifest_schema "$RELEASE_MANIFEST_FILE" 'bubbles framework-write-guard' || exit 1

bubbles_read_release_manifest_summary "$RELEASE_MANIFEST_FILE" \
  manifest_version \
  manifest_git_sha \
  manifest_profiles \
  manifest_interop \
  manifest_managed_count
bubbles_read_install_provenance_summary "$INSTALL_PROVENANCE_FILE" \
  install_version \
  install_mode \
  source_ref \
  source_git_sha \
  source_dirty

info "Checking downstream framework-managed files against .github/bubbles/.checksums"

info "Installed release manifest: version=${manifest_version} gitSha=${manifest_git_sha}"
info "Install provenance: mode=${install_mode} sourceRef=${source_ref} sourceGitSha=${source_git_sha} dirty=${source_dirty}"
info "Supported profiles: ${manifest_profiles}"
info "Supported interop sources: ${manifest_interop}"

if [[ -n "$install_version" && -n "$manifest_version" && "$install_version" != "$manifest_version" ]]; then
  fail_line "Install provenance version (${install_version}) does not match release manifest version (${manifest_version})"
fi

if [[ "$source_dirty" == "true" ]]; then
  warn_line "Installed from a dirty local source checkout. This is not a clean published release install."
fi

while IFS=$'\t' read -r expected_hash relative_path; do
  [[ -n "$expected_hash" ]] || continue
  [[ "$expected_hash" == \#* ]] && continue
  [[ -n "$relative_path" ]] || continue

  target_file="$MANAGED_ROOT/$relative_path"
  if [[ ! -f "$target_file" ]]; then
    fail_line "Missing framework-managed file: $relative_path"
    continue
  fi

  actual_hash="$(bubbles_sha256_file "$target_file")"
  if [[ "$actual_hash" != "$expected_hash" ]]; then
    fail_line "Framework-managed file drift detected: $relative_path"
    [[ "$quiet" == "true" ]] || {
      echo "   Expected: $expected_hash"
      echo "   Actual:   $actual_hash"
    }
  fi
done < "$CHECKSUM_FILE"

if [[ "$violations" -gt 0 ]]; then
  [[ "$quiet" == "true" ]] || {
    echo ""
    echo "Downstream repos must not directly author changes in framework-managed Bubbles files."
    echo "Use a project-owned proposal instead: .github/bubbles-project/proposals/"
    echo "Suggested flow: bubbles framework-proposal <slug>"
    echo "Then implement the change in the Bubbles source repo and refresh this repo's framework install."
  }
  exit 1
fi

pass "Managed-file integrity: downstream framework-managed files still match the installed upstream snapshot"