#!/usr/bin/env bash
# generate-validation-checks.sh — DERIVE the validation closure map.
#
# Capability: declared-input-closure-validation
#
# WHY THIS EXISTS
# Change selection and cache reuse were both keyed on a BASENAME PAIR: a
# selftest `X-selftest.sh` was assumed to own exactly `X.sh` and nothing else.
# That assumption is a guess, and it was wrong in two directions at once.
# Changing `bubbles/registry/gates.yaml` skipped every selftest that reads it,
# because no basename changed. Changing `guard-lib.sh` served a cached PASS to
# every consumer that sources it, for the same reason. Both failures report
# success about work that was never re-examined.
#
# The fix is not a better guess. `bubbles/registry/validation-checks.yaml` is
# GENERATED by tracing the references that actually exist in the source, using
# the technique `gates-block-reader-lint.sh` proved: ask what a script really
# depends on rather than what its name implies. A hand-written closure would be
# a fourth guess, so this generator owns the file and `--check` refuses a hand
# edit.
#
# WHAT A CLOSURE CONTAINS
#   scripts       every `.sh` reachable through `bash`/`source`/`.` references,
#                 transitively
#   inputs        every registry, schema, template or fixture file named by a
#                 literal path token in any script in that transitive set
#   commands      external tools the closure calls (`yq`, `jq`, `git`, ...);
#                 their VERSIONS join the runtime digest, so a tool upgrade
#                 invalidates reuse
#   platform      `uname -s`, and the framework VERSION, both added at digest
#                 time by validation-closure.sh
#
# HONEST INCOMPLETENESS IS THE POINT
# A check that walks the repository (`$REPO_ROOT`, `find`, `git -C`) does not
# have an enumerable input set: its input is the tree, which is the thing that
# changes. Those checks are recorded `closureComplete: false`. An incomplete
# closure is NEVER reused and ALWAYS executed. Guessing a closure for them would
# reintroduce exactly the staleness this file removes, so the generator records
# that it does not know instead of inventing an answer.
#
# Usage:
#   bash bubbles/scripts/generate-validation-checks.sh            # write
#   bash bubbles/scripts/generate-validation-checks.sh --check    # verify
#   bash bubbles/scripts/generate-validation-checks.sh --stdout   # print
#
# Exit codes:
#   0  written, or --check found the committed file identical to the derivation
#   1  --check found drift (a hand edit, or a stale committed file)
#   2  usage error or a required input could not be read

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
NAME="generate-validation-checks"
MODE="write"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo-root)
      shift
      REPO_ROOT="${1:-}"
      ;;
    --check) MODE="check" ;;
    --stdout) MODE="stdout" ;;
    --classify-closure-tree) MODE="classify-closure-tree" ;;
    -h | --help)
      printf 'usage: %s.sh [--repo-root DIR] [--check|--stdout|--classify-closure-tree]\n' "$NAME"
      printf 'Derives bubbles/registry/validation-checks.yaml by tracing real references.\n'
      printf -- '--classify-closure-tree (IMP-059 SCOPE-1): for every closureComplete: false\n'
      printf 'selftest, print why: genuine-tree-walk, candidate-false-negative, or\n'
      printf 'closure-unresolved. Read-only; changes no generator output.\n'
      exit 0
      ;;
    *)
      printf '%s: unsupported flag "%s". This generator has no bypass.\n' "$NAME" "$1" >&2
      exit 2
      ;;
  esac
  shift || true
done

VALIDATOR="$REPO_ROOT/bubbles/scripts/framework-validate.sh"
TARGET="$REPO_ROOT/bubbles/registry/validation-checks.yaml"

[[ -f "$VALIDATOR" ]] || {
  printf '%s: framework-validate.sh not found: %s\n' "$NAME" "$VALIDATOR" >&2
  exit 2
}

# --- reference extraction ----------------------------------------------------
#
# One awk pass per file. Full-line comments are stripped first: prose ABOUT a
# dependency is not a dependency, and without that rule the header of every
# script in this repository would enrol it as a reader of everything it explains.
#
# PORTABILITY. Every pattern below uses BRACKET EXPRESSIONS, never `\{` or `\$`.
# BSD awk rejects `\{` outright, and the first version of this file swallowed
# that error with `2>/dev/null`: the extractor aborted, every closure came back
# empty, and the generator still exited 0 with a registry that recorded no
# dependencies at all. A silent empty derivation is worse than the basename
# guess it replaces, so extractor errors now propagate and extractor_probe()
# refuses to generate anything if the scanner has gone inert.
extract_refs() {
  local file="$1"
  {
    LC_ALL=C awk '
    function emit(tok) { if (tok != "") print tok }
    {
      line = $0
      if (line ~ /^[ \t]*#/) next
      rest = line
      while (match(rest, /([$][{]?SCRIPT_DIR[}]?|[$][{]?REPO_ROOT[}]?|[$][{]?repo_root[}]?|bubbles|agents|skills|instructions|tests|templates|docs|[.]specify)[A-Za-z0-9_.\/-]*[.](sh|py|yaml|yml|json|txt|md|mjs)/)) {
        emit(substr(rest, RSTART, RLENGTH))
        rest = substr(rest, RSTART + RLENGTH)
      }
    }
    ' "$file"
    if [[ "$file" == *.py ]]; then
      extract_python_path_refs "$file"
    fi
  } | LC_ALL=C sort -u
}

# Python checks use pathlib rather than shell-rooted strings. Trace the local
# HERE/ROOT path expressions so Python validation drivers receive the same
# dependency closure as shell drivers. Each quoted filename is emitted
# separately; this also handles list comprehensions such as
# `HERE.parent / "schemas" / name for name in ("a.json", "b.json")`.
extract_python_path_refs() {
  local file="$1"
  LC_ALL=C awk '
    /^[ \t]*#/ { next }
    {
      line = $0
      prefix = ""
      start = 0
      if (match(line, /HERE[.]parent[.]parent[ \t]*\//)) {
        start = RSTART + RLENGTH
      } else if (match(line, /HERE[.]parent[ \t]*\//)) {
        prefix = "bubbles"
        start = RSTART + RLENGTH
      } else if (match(line, /HERE[ \t]*\//)) {
        prefix = "bubbles/scripts"
        start = RSTART + RLENGTH
      } else if (match(line, /ROOT[ \t]*\//)) {
        prefix = "bubbles"
        start = RSTART + RLENGTH
      } else {
        next
      }

      rest = substr(line, start)
      dirs = ""
      while (match(rest, /"[A-Za-z0-9_.-]+"/)) {
        token = substr(rest, RSTART + 1, RLENGTH - 2)
        rest = substr(rest, RSTART + RLENGTH)
        if (token ~ /[.](sh|py|yaml|yml|json|txt|md|mjs)$/) {
          path = prefix
          if (dirs != "") path = (path == "" ? dirs : path "/" dirs)
          path = (path == "" ? token : path "/" token)
          print path
        } else {
          dirs = (dirs == "" ? token : dirs "/" token)
        }
      }
    }
  ' "$file"
}

# The extractor is the whole derivation. If it stops matching, every closure
# silently becomes "depends on nothing", which reuses stale results forever.
# This probe feeds it the two reference shapes the framework actually uses and
# refuses to write a registry when either one is lost.
extractor_probe() {
  local probe_dir probe_file out
  probe_dir="$(mktemp -d)"
  probe_file="$probe_dir/probe.sh"
  # The third line exercises the $REPO_ROOT-rooted shape. Its basename is
  # DELIBERATELY synthetic: naming a real source-only regression test here made
  # every mechanical reader of this file -- payload-closure-guard.sh among them
  # -- read the probe fixture as a runtime dependency on a file that never ships.
  # The probe tests the SCANNER, so any path of the right shape proves it.
  {
    printf 'source "$SCRIPT_DIR/guard-lib.sh"\n'
    printf 'READER="$SCRIPT_DIR/scenario-reference-reader.py"\n'
    printf 'REG="$SCRIPT_DIR/../registry/gates.yaml"\n'
    printf 'bash "$REPO_ROOT/tests/regression/probe_extractor_fixture.sh"\n'
  } >"$probe_file"
  out="$(extract_refs "$probe_file")"
  rm -rf "$probe_dir"
  if [[ "$out" != *'guard-lib.sh'* || "$out" != *'scenario-reference-reader.py'* || "$out" != *'gates.yaml'* || "$out" != *'probe_extractor_fixture.sh'* ]]; then
    printf '%s: the reference extractor matched nothing on its own probe.\n' "$NAME" >&2
    printf '%s: refusing to write a closure map derived by a scanner that is not working.\n' "$NAME" >&2
    return 1
  fi
  return 0
}

# A reference the tracer cannot resolve to a literal path. `bash "$SOMEVAR"`
# where SOMEVAR is not a rooted literal means the input set is not enumerable
# from the source, and the closure must say so.
#
# Variable indirection is the NORMAL shape here — a selftest writes
# `GUARD="$SCRIPT_DIR/x.sh"` once and then invokes `bash "$GUARD"` many times —
# so the dispatch test first collects which variables hold a rooted literal.
# Without that step almost every selftest reads as unresolved, the closure map
# says it knows nothing about anything, and the mechanism becomes decoration.
resolved_path_vars() {
  local file="$1"
  LC_ALL=C awk '
    /^[ \t]*#/ { next }
    match($0, /^[ \t]*[A-Za-z_][A-Za-z0-9_]*=["]?[$][{]?(SCRIPT_DIR|REPO_ROOT|repo_root)[}]?\//) {
      name = $0
      sub(/^[ \t]*/, "", name)
      sub(/=.*$/, "", name)
      print name
    }
  ' "$file" | LC_ALL=C sort -u
}

has_unresolved_dispatch() {
  local file="$1" resolved="|" name
  while IFS= read -r name; do
    [[ -n "$name" ]] && resolved+="$name|"
  done < <(resolved_path_vars "$file")

  LC_ALL=C awk -v resolved="$resolved" '
    /^[ \t]*#/ { next }
    {
      rest = $0
      while (match(rest, /(^|[^A-Za-z0-9_])(bash|source)[ \t]+"?[$][{]?[A-Za-z_][A-Za-z0-9_]*[}]?/)) {
        tok = substr(rest, RSTART, RLENGTH)
        rest = substr(rest, RSTART + RLENGTH)
        # The next character decides: a "/" means a rooted literal path follows.
        if (substr(rest, 1, 1) == "/") continue
        name = tok
        sub(/^.*[$][{]?/, "", name)
        sub(/[}]?$/, "", name)
        if (name == "SCRIPT_DIR" || name == "REPO_ROOT" || name == "repo_root") continue
        if (index(resolved, "|" name "|") > 0) continue
        found = 1
      }
    }
    END { exit(found ? 0 : 1) }
  ' "$file"
}

# A check that walks the repository has the TREE as its input. That is not a
# closure, and pretending otherwise is the staleness this file removes.
reads_working_tree() {
  local file="$1"
  LC_ALL=C awk '
    /^[ \t]*#/ { next }
    /[$][{]?REPO_ROOT[}]?|[$][{]?repo_root[}]?|git -C|bubbles_pruned_find/ { found = 1 }
    END { exit(found ? 0 : 1) }
  ' "$file"
}

# IMP-059 SCOPE-1 (read-only diagnostic; does not affect closureComplete or the
# committed registry): reads_working_tree() above flags a file on TEXTUAL
# presence of $REPO_ROOT/$repo_root ANYWHERE, which cannot distinguish an
# actual tree-walk (`git -C`, `bubbles_pruned_find`, an unrooted `find`) from a
# BOUNDED literal-path reference such as "$REPO_ROOT/bubbles/scripts/foo.sh" —
# a reference scan_file()/normalize_ref() already resolve into a concrete,
# enumerable dependency. This prints, per non-comment line of one file, either
# "unbounded" (a real walk marker, or a $REPO_ROOT/$repo_root token with no
# resolvable literal path after it) or "bounded:<path>" (a $REPO_ROOT/$repo_root
# token immediately followed by a literal path that resolves to a real file).
# One unbounded line anywhere in a check's tree-flagged closure members is
# enough to call the whole check a genuine tree-walk; --classify-closure-tree
# below applies that rule.
tree_match_kind() {
  local file="$1" abs
  abs="$REPO_ROOT/$file"
  [[ -f "$abs" ]] || {
    printf 'unbounded\n'
    return 0
  }
  LC_ALL=C awk '
    /^[ \t]*#/ { next }
    /git -C|bubbles_pruned_find/ { print "unbounded"; next }
    {
      rest = $0
      while (match(rest, /[$][{]?(REPO_ROOT|repo_root)[}]?/)) {
        after = substr(rest, RSTART + RLENGTH)
        rest = substr(rest, RSTART + RLENGTH)
        if (substr(after, 1, 1) != "/") { print "unbounded"; continue }
        tail = substr(after, 2)
        if (match(tail, /^[A-Za-z0-9_.\/-]+/)) {
          print "bounded:" substr(tail, RSTART, RLENGTH)
        } else {
          print "unbounded"
        }
      }
    }
  ' "$abs"
}

# Resolves each token tree_match_kind() marked "bounded:<path>" against the
# repo root, collapsing one `dir/../` hop the same way normalize_ref() does. A
# bounded token that does NOT resolve to a real file is treated as unbounded —
# an unverifiable claim of boundedness is not evidence of one.
classify_closure_tree_member() {
  local member="$1" line cand collapsed head tail
  local verdict="bounded"
  while IFS= read -r line; do
    [[ -n "$line" ]] || continue
    case "$line" in
      unbounded)
        verdict="unbounded"
        break
        ;;
      bounded:*)
        cand="${line#bounded:}"
        collapsed="$cand"
        while [[ "$collapsed" == *"/../"* ]]; do
          head="${collapsed%%/../*}"
          tail="${collapsed#*/../}"
          head="${head%/*}"
          if [[ -n "$head" ]]; then collapsed="$head/$tail"; else collapsed="$tail"; fi
        done
        if [[ ! -e "$REPO_ROOT/$collapsed" ]]; then
          verdict="unbounded"
          break
        fi
        ;;
    esac
  done < <(tree_match_kind "$member")
  printf '%s\n' "$verdict"
}

# Scripts this file invokes with NO argument after the path.
#
# This is the discriminator that decides whether a dependency's tree-reading is
# also the CALLER's. A selftest that runs `bash "$SCRIPT_DIR/guard.sh" "$fixture"`
# supplies the tree it is pointed at, so the guard's ability to walk a repository
# adds nothing the caller's own closure does not already contain. A caller that
# runs `bash "$SCRIPT_DIR/guard.sh"` bare lets the guard resolve its OWN repo
# root, and that IS the working tree entering the caller's input set.
bare_invoked_scripts() {
  local file="$1"
  LC_ALL=C awk '
    /^[ \t]*#/ { next }
    {
      rest = $0
      while (match(rest, /(^|[^A-Za-z0-9_])(bash|sh|source|[.])[ \t]+"?[$][{]?(SCRIPT_DIR|REPO_ROOT|repo_root)[}]?\/[A-Za-z0-9_.\/-]*[.]sh"?/)) {
        tok = substr(rest, RSTART, RLENGTH)
        rest = substr(rest, RSTART + RLENGTH)
        tail = rest
        sub(/^[ \t]*/, "", tail)
        # Anything other than end-of-command means an argument follows.
        if (tail != "" && tail !~ /^([;)&|<>#]|2>)/) continue
        sub(/^[^$]*/, "", tok)
        gsub(/"/, "", tok)
        print tok
      }
    }
  ' "$file" | LC_ALL=C sort -u
}

KNOWN_COMMANDS="yq jq git python3 node npx shellcheck shfmt sha256sum shasum perl"

extract_commands() {
  local file="$1" tool
  for tool in $KNOWN_COMMANDS; do
    if LC_ALL=C grep -qE "(command -v|which) $tool|(^|[^A-Za-z0-9_-])$tool " "$file" 2>/dev/null; then
      printf '%s\n' "$tool"
    fi
  done
}

# Normalize a raw token into a repo-relative path, or print nothing.
normalize_ref() {
  local raw="$1" path=""
  case "$raw" in
    '${SCRIPT_DIR}'* | '$SCRIPT_DIR'*)
      path="${raw#*SCRIPT_DIR}"
      path="${path#\}}"
      path="${path#/}"
      path="bubbles/scripts/$path"
      ;;
    '${REPO_ROOT}'* | '$REPO_ROOT'* | '${repo_root}'* | '$repo_root'*)
      path="${raw#*[Rr][Ee][Pp][Oo]_[Rr][Oo][Oo][Tt]}"
      path="${path#\}}"
      path="${path#/}"
      ;;
    bubbles/* | agents/* | skills/* | instructions/* | tests/* | templates/* | docs/* | .specify/*)
      path="$raw"
      ;;
    *) return 0 ;;
  esac
  # Collapse a single `dir/../` hop, which is how scripts reach the registry.
  while [[ "$path" == *"/../"* ]]; do
    local head tail
    head="${path%%/../*}"
    tail="${path#*/../}"
    head="${head%/*}"
    if [[ -n "$head" ]]; then path="$head/$tail"; else path="$tail"; fi
  done
  [[ -n "$path" ]] || return 0
  [[ -e "$REPO_ROOT/$path" ]] || return 0
  printf '%s\n' "$path"
}

declare -A FILE_SCRIPTS=()
declare -A FILE_DATA=()
declare -A FILE_COMMANDS=()
declare -A FILE_UNRESOLVED=()
declare -A FILE_TREE=()
declare -A FILE_BARE=()
declare -A FILE_SCANNED=()

scan_file() {
  local path="$1"
  [[ -n "${FILE_SCANNED[$path]:-}" ]] && return 0
  FILE_SCANNED["$path"]=1
  local abs="$REPO_ROOT/$path"
  [[ -f "$abs" ]] || return 0

  local scripts="" data="" ref norm
  while IFS= read -r ref; do
    [[ -n "$ref" ]] || continue
    norm="$(normalize_ref "$ref")"
    [[ -n "$norm" ]] || continue
    [[ "$norm" == "$path" ]] && continue
    case "$norm" in
      *.sh | *.py) scripts+="$norm"$'\n' ;;
      *) data+="$norm"$'\n' ;;
    esac
  done < <(extract_refs "$abs")

  FILE_SCRIPTS["$path"]="$(printf '%s' "$scripts" | LC_ALL=C sort -u)"
  FILE_DATA["$path"]="$(printf '%s' "$data" | LC_ALL=C sort -u)"
  FILE_COMMANDS["$path"]="$(extract_commands "$abs" | LC_ALL=C sort -u)"
  if has_unresolved_dispatch "$abs"; then FILE_UNRESOLVED["$path"]=1; else FILE_UNRESOLVED["$path"]=0; fi
  if reads_working_tree "$abs"; then FILE_TREE["$path"]=1; else FILE_TREE["$path"]=0; fi

  local bare="" invoked
  while IFS= read -r invoked; do
    [[ -n "$invoked" ]] || continue
    norm="$(normalize_ref "$invoked")"
    [[ -n "$norm" ]] && bare+="$norm"$'\n'
  done < <(bare_invoked_scripts "$abs")
  FILE_BARE["$path"]="$bare"
}

# --- closure walk ------------------------------------------------------------
CLOSURE_SCRIPTS=""
CLOSURE_DATA=""
CLOSURE_COMMANDS=""
CLOSURE_UNRESOLVED=0
CLOSURE_TREE=0

walk_closure() {
  local root="$1"
  CLOSURE_SCRIPTS=""
  CLOSURE_DATA=""
  CLOSURE_COMMANDS=""
  CLOSURE_UNRESOLVED=0
  CLOSURE_TREE=0
  local -A seen=()
  local closure_bare=$'\n'
  local queue=("$root") current next
  while [[ "${#queue[@]}" -gt 0 ]]; do
    current="${queue[0]}"
    queue=("${queue[@]:1}")
    [[ -n "${seen[$current]:-}" ]] && continue
    seen["$current"]=1
    scan_file "$current"
    CLOSURE_SCRIPTS+="$current"$'\n'
    [[ -n "${FILE_DATA[$current]:-}" ]] && CLOSURE_DATA+="${FILE_DATA[$current]}"$'\n'
    [[ -n "${FILE_COMMANDS[$current]:-}" ]] && CLOSURE_COMMANDS+="${FILE_COMMANDS[$current]}"$'\n'
    [[ "${FILE_UNRESOLVED[$current]:-0}" == "1" ]] && CLOSURE_UNRESOLVED=1
    [[ -n "${FILE_BARE[$current]:-}" ]] && closure_bare+="${FILE_BARE[$current]}"
    while IFS= read -r next; do
      [[ -n "$next" ]] || continue
      [[ -n "${seen[$next]:-}" ]] && continue
      queue+=("$next")
    done <<<"${FILE_SCRIPTS[$current]:-}"
  done

  # Tree-reading is a property of the CHECK, not of everything the check can
  # reach. OR-ing the flag across the whole closure marked 271 of 332 checks
  # "inputs not enumerable" -- including selftests whose entire input set is two
  # files -- purely because some guard they drive against a mktemp fixture can
  # also walk a repository when pointed at one. An unknown closure is affected
  # by every change, so `--changed-only` degraded to the full suite: an
  # over-approximation that made the selection worthless rather than safe.
  #
  # The tree enters a check's inputs when the CHECK ROOT itself reads it, or
  # when the root's closure invokes a tree-reading script BARE, letting that
  # script resolve its own repo root. Both are recorded; a dependency handed an
  # explicit fixture path is not.
  [[ "${FILE_TREE[$root]:-0}" == "1" ]] && CLOSURE_TREE=1
  if [[ "$CLOSURE_TREE" -eq 0 ]]; then
    local member
    while IFS= read -r member; do
      [[ -n "$member" ]] || continue
      [[ "${FILE_TREE[$member]:-0}" == "1" ]] || continue
      case "$closure_bare" in
        *$'\n'"$member"$'\n'*)
          CLOSURE_TREE=1
          break
          ;;
      esac
    done <<<"$CLOSURE_SCRIPTS"
  fi

  CLOSURE_SCRIPTS="$(printf '%s' "$CLOSURE_SCRIPTS" | LC_ALL=C sort -u)"
  CLOSURE_DATA="$(printf '%s' "$CLOSURE_DATA" | LC_ALL=C sort -u)"
  CLOSURE_COMMANDS="$(printf '%s' "$CLOSURE_COMMANDS" | LC_ALL=C sort -u)"
}

# --- registration extraction -------------------------------------------------
#
# Logical lines: framework-validate.sh continues registrations with a trailing
# backslash, so a physical-line reader would lose the script token on the
# continued ones and silently under-report the schedule.
registrations() {
  LC_ALL=C awk '
    {
      line = $0
      sub(/^[ \t]+/, "", line)
      if (pending != "") { line = pending " " line; pending = "" }
      if (line ~ /\\$/) { sub(/\\$/, "", line); pending = line; next }
      if (line !~ /^run_check(_self_only)?[ \t]/) next
      print line
    }
  ' "$VALIDATOR"
}

slug_for() {
  local path="$1" slug
  slug="${path%.*}"
  slug="$(printf '%s' "$slug" | LC_ALL=C tr -c 'A-Za-z0-9' '-')"
  while [[ "$slug" == *--* ]]; do slug="${slug//--/-}"; done
  slug="${slug#-}"
  slug="${slug%-}"
  printf 'vc-%s' "$slug"
}

emit_registry() {
  local generated_from
  generated_from="$(cd "$REPO_ROOT" && git rev-parse --short HEAD 2>/dev/null || echo unknown)"

  printf '# GENERATED:VALIDATION_CHECKS — do not edit by hand.\n'
  printf '# Regenerate with: bash bubbles/scripts/generate-validation-checks.sh\n'
  printf '# Verify with:     bash bubbles/scripts/generate-validation-checks.sh --check\n'
  printf '#\n'
  printf '# Every closure below was DERIVED by tracing bash/source references and\n'
  printf '# literal path tokens out of the source. None of it is hand-authored, and a\n'
  printf '# hand edit is refused by --check. `closureComplete: false` means the check\n'
  printf '# reads the working tree, so its inputs are not enumerable: it is always\n'
  printf '# executed and never reused.\n'
  printf 'schemaVersion: 1\n'
  printf 'generator: bubbles/scripts/generate-validation-checks.sh\n'
  printf 'source: bubbles/scripts/framework-validate.sh\n'
  printf 'checks:\n'

  local line label script token id seen_ids=" " suffix
  while IFS= read -r line; do
    [[ -n "$line" ]] || continue
    # Label is the first double-quoted field.
    label="${line#*\"}"
    label="${label%%\"*}"
    script=""
    for token in $line; do
      token="${token//\"/}"
      case "$token" in
        *SCRIPT_DIR/*.sh | *REPO_ROOT/*.sh | *SCRIPT_DIR/*.py | *REPO_ROOT/*.py)
          script="$(normalize_ref "$token")"
          [[ -n "$script" ]] && break
          ;;
      esac
    done
    [[ -n "$script" ]] || continue

    id="$(slug_for "$script")"
    if [[ "$seen_ids" == *" $id "* ]]; then
      suffix=2
      while [[ "$seen_ids" == *" $id-$suffix "* ]]; do suffix=$((suffix + 1)); done
      id="$id-$suffix"
    fi
    seen_ids+="$id "

    walk_closure "$script"
    local complete="true"
    [[ "$CLOSURE_UNRESOLVED" == "1" ]] && complete="false"
    [[ "$CLOSURE_TREE" == "1" ]] && complete="false"

    printf '%s\n' "  $id:"
    printf '    script: %s\n' "$script"
    printf '    label: "%s"\n' "$label"
    printf '    closureComplete: %s\n' "$complete"
    printf '    inputs:\n'
    local item
    while IFS= read -r item; do
      [[ -n "$item" ]] && printf '    - %s\n' "$item"
    done <<<"$CLOSURE_SCRIPTS"
    while IFS= read -r item; do
      [[ -n "$item" ]] && printf '    - %s\n' "$item"
    done <<<"$CLOSURE_DATA"
    # `commands:` and a bare `[]` on the NEXT line at the SAME indent is not a
    # value -- YAML reads the `[]` as a sibling key and refuses the document.
    # An empty flow sequence has to sit on the key's own line.
    if [[ -z "$CLOSURE_COMMANDS" ]]; then
      printf '    commands: []\n'
    else
      printf '    commands:\n'
      while IFS= read -r item; do
        [[ -n "$item" ]] && printf '    - %s\n' "$item"
      done <<<"$CLOSURE_COMMANDS"
    fi
  done < <(registrations)

  # The discovery sweep in framework-validate.sh schedules every
  # bubbles/scripts/*-selftest.sh that no enumerated check already names and the
  # denylist does not deny. Those runs are SCHEDULED CHECKS, so they need stable
  # ids too — enumerating only the hand-written registrations would leave the
  # largest part of the suite outside the closure map and quietly outside every
  # rule built on it.
  local denylist="$REPO_ROOT/bubbles/registry/selftest-denylist.txt"
  local denied=$'\n'
  if [[ -r "$denylist" ]]; then
    local deny_line trimmed
    while IFS= read -r deny_line || [[ -n "$deny_line" ]]; do
      trimmed="${deny_line#"${deny_line%%[![:space:]]*}"}"
      [[ -z "$trimmed" || "$trimmed" == '#'* ]] && continue
      denied+="$trimmed"$'\n'
    done <"$denylist"
  fi

  local candidate base
  for candidate in "$REPO_ROOT"/bubbles/scripts/*-selftest.sh; do
    [[ -f "$candidate" ]] || continue
    base="$(basename "$candidate")"
    [[ "$denied" == *$'\n'"$base"$'\n'* ]] && continue
    script="bubbles/scripts/$base"
    id="$(slug_for "$script")"
    [[ "$seen_ids" == *" $id "* ]] && continue
    seen_ids+="$id "

    walk_closure "$script"
    local sweep_complete="true"
    [[ "$CLOSURE_UNRESOLVED" == "1" ]] && sweep_complete="false"
    [[ "$CLOSURE_TREE" == "1" ]] && sweep_complete="false"

    printf '%s\n' "  $id:"
    printf '    script: %s\n' "$script"
    printf '    label: "Discovered selftest: %s"\n' "$base"
    printf '    closureComplete: %s\n' "$sweep_complete"
    printf '    inputs:\n'
    while IFS= read -r item; do
      [[ -n "$item" ]] && printf '    - %s\n' "$item"
    done <<<"$CLOSURE_SCRIPTS"
    while IFS= read -r item; do
      [[ -n "$item" ]] && printf '    - %s\n' "$item"
    done <<<"$CLOSURE_DATA"
    # Same as above: an empty sequence must not start on the following line.
    if [[ -z "$CLOSURE_COMMANDS" ]]; then
      printf '    commands: []\n'
    else
      printf '    commands:\n'
      while IFS= read -r item; do
        [[ -n "$item" ]] && printf '    - %s\n' "$item"
      done <<<"$CLOSURE_COMMANDS"
    fi
  done

  printf 'derivedAt: %s\n' "$generated_from"
}

# IMP-059 SCOPE-1 — read-only closure-tree classification. Re-derives, from
# the SAME emit_registry() output every other mode uses, why each
# closureComplete: false SELFTEST is incomplete: a genuine tree-walk, a
# candidate false-negative (see tree_match_kind() above), or CLOSURE_UNRESOLVED
# (an unresolved bash/source variable, a distinct and unrelated reason). Prints
# nothing to TARGET and writes nothing; the caller redirects stdout to the
# checked-in classification manifest.
classify_closure_tree() {
  local registry
  registry="$(emit_registry)"

  local line pending_script="" bucket member verdict overall any_member
  while IFS= read -r line; do
    case "$line" in
      "    script: "*)
        pending_script="${line#    script: }"
        ;;
      "    closureComplete: true")
        pending_script=""
        ;;
      "    closureComplete: false")
        case "$pending_script" in
          *-selftest.sh | *-selftest.py) ;;
          *)
            pending_script=""
            continue
            ;;
        esac

        walk_closure "$pending_script"
        if [[ "$CLOSURE_TREE" != "1" && "$CLOSURE_UNRESOLVED" == "1" ]]; then
          bucket="closure-unresolved"
        else
          overall="genuine-tree-walk"
          any_member=0
          while IFS= read -r member; do
            [[ -n "$member" ]] || continue
            [[ "${FILE_TREE[$member]:-0}" == "1" ]] || continue
            any_member=1
            verdict="$(classify_closure_tree_member "$member")"
            if [[ "$verdict" == "bounded" ]]; then
              overall="candidate-false-negative"
            else
              overall="genuine-tree-walk"
              break
            fi
          done <<<"$CLOSURE_SCRIPTS"
          # CLOSURE_TREE=1 with no flagged member is not expected to occur; a
          # conservative default (genuine-tree-walk) is safer than a silent
          # reclassification the walk itself cannot substantiate.
          [[ "$any_member" == "0" ]] && overall="genuine-tree-walk"
          bucket="$overall"
          [[ "$CLOSURE_UNRESOLVED" == "1" && "$bucket" == "candidate-false-negative" ]] && bucket="candidate-false-negative+closure-unresolved"
        fi
        printf '%s\t%s\n' "$pending_script" "$bucket"
        pending_script=""
        ;;
    esac
  done <<<"$registry"
}

extractor_probe || exit 2

case "$MODE" in
  stdout)
    emit_registry
    ;;
  classify-closure-tree)
    classify_closure_tree
    ;;
  check)
    if [[ ! -f "$TARGET" ]]; then
      printf '%s: %s is missing; run the generator.\n' "$NAME" "$TARGET" >&2
      exit 1
    fi
    tmp="$(mktemp)"
    trap 'rm -f "$tmp"' EXIT
    emit_registry >"$tmp"
    # `derivedAt` records the revision the map was derived at. It is provenance,
    # not content, so it is excluded from the drift comparison; otherwise every
    # commit would report drift and the check would be ignored within a week.
    if LC_ALL=C diff -q \
      <(LC_ALL=C grep -v '^derivedAt: ' "$TARGET") \
      <(LC_ALL=C grep -v '^derivedAt: ' "$tmp") >/dev/null 2>&1; then
      printf '%s: OK — the committed closure map matches the derivation.\n' "$NAME"
      exit 0
    fi
    printf '%s: DRIFT — bubbles/registry/validation-checks.yaml does not match the derivation.\n' "$NAME" >&2
    printf '%s: this file is GENERATED. A hand edit is refused; regenerate it instead:\n' "$NAME" >&2
    printf '%s:   bash bubbles/scripts/generate-validation-checks.sh\n' "$NAME" >&2
    LC_ALL=C diff \
      <(LC_ALL=C grep -v '^derivedAt: ' "$TARGET") \
      <(LC_ALL=C grep -v '^derivedAt: ' "$tmp") >&2 || true
    exit 1
    ;;
  write)
    mkdir -p "$(dirname "$TARGET")"
    tmp="$(mktemp)"
    trap 'rm -f "$tmp"' EXIT
    emit_registry >"$tmp"
    cp "$tmp" "$TARGET"
    printf '%s: wrote %s\n' "$NAME" "$TARGET"
    exit 0
    ;;
esac
