#!/usr/bin/env bash
# retro-framework-health.sh — framework self-observation analysis.
#
# Reads bubbles' own usage signals and emits an improvement proposal under
# improvements/IMP-NNN-<slug>.md. NEVER mutates bubbles/, agents/, or
# bubbles/workflows.yaml.
#
# Inputs (all read-only):
#   .specify/runtime/framework-events.jsonl  — agent/workflow events (per line JSON)
#   .specify/runtime/workflow-runs.json      — per-run records (JSON array)
#   bubbles/capability-ledger.yaml           — capability staleness ledger
#
# Output:
#   improvements/IMP-<NNN>-<slug>.md         — markdown proposal
#
# Exit codes:
#   0 — proposal written (or "no signal" message if inputs absent/empty)
#   1 — hard tooling failure (missing jq/yq/find)
#
# Usage:
#   bash bubbles/scripts/retro-framework-health.sh [repo-root] [--slug <slug>] [--out-dir <dir>]

set -euo pipefail

REPO_ROOT="${1:-.}"
shift || true

SLUG="framework-health-$(date -u +%Y%m%d)"
OUT_DIR=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --slug) SLUG="$2"; shift 2 ;;
    --out-dir) OUT_DIR="$2"; shift 2 ;;
    -h|--help)
      cat <<'EOF'
retro-framework-health.sh — framework self-observation
Usage: bash retro-framework-health.sh [repo-root] [--slug <slug>] [--out-dir <dir>]
Reads .specify/runtime/framework-events.jsonl + workflow-runs.json + capability-ledger.yaml
Writes improvements/IMP-NNN-<slug>.md (proposal-first; no auto-mutation of framework files).
EOF
      exit 0
      ;;
    *) shift ;;
  esac
done

[[ -z "$OUT_DIR" ]] && OUT_DIR="$REPO_ROOT/improvements"
mkdir -p "$OUT_DIR"

EVENTS_FILE="$REPO_ROOT/.specify/runtime/framework-events.jsonl"
RUNS_FILE="$REPO_ROOT/.specify/runtime/workflow-runs.json"
LEDGER_FILE="$REPO_ROOT/bubbles/capability-ledger.yaml"

# Determine next IMP number
existing="$(find "$OUT_DIR" -maxdepth 1 -name 'IMP-*-*.md' -type f 2>/dev/null | sed -E 's|.*IMP-([0-9]+)-.*|\1|' | sort -n | tail -1 || true)"
if [[ -z "$existing" ]]; then
  next_num=1
else
  next_num=$((existing + 1))
fi
OUT_FILE="$(printf "%s/IMP-%03d-%s.md" "$OUT_DIR" "$next_num" "$SLUG")"

# Top failed gates from events file (events may carry gate=<G0XX> outcome=fail)
top_failed_gates=""
if [[ -f "$EVENTS_FILE" ]] && command -v jq >/dev/null 2>&1; then
  top_failed_gates="$(jq -r 'select(.outcome=="fail" and .gate != null) | .gate' "$EVENTS_FILE" 2>/dev/null \
    | sort | uniq -c | sort -rn | head -5 | awk '{printf "- %s (%d failures)\n", $2, $1}' || true)"
fi
[[ -z "$top_failed_gates" ]] && top_failed_gates="- (no gate failure data found in framework-events.jsonl)"

# Stalled modes from workflow-runs.json (mode with outcome != completed)
stalled_modes=""
if [[ -f "$RUNS_FILE" ]] && command -v jq >/dev/null 2>&1; then
  stalled_modes="$(jq -r '.[]? | select(.outcome != "completed" and .outcome != null) | .mode' "$RUNS_FILE" 2>/dev/null \
    | sort | uniq -c | sort -rn | head -3 | awk '{printf "- %s (%d non-completed runs)\n", $2, $1}' || true)"
fi
[[ -z "$stalled_modes" ]] && stalled_modes="- (no non-completed run data found in workflow-runs.json)"

# Stale capabilities (lastValidated > 90 days)
stale_caps=""
if [[ -f "$LEDGER_FILE" ]] && command -v yq >/dev/null 2>&1; then
  cutoff="$(date -u -d '90 days ago' +%FT%TZ 2>/dev/null || date -u -v-90d +%FT%TZ 2>/dev/null || true)"
  if [[ -n "$cutoff" ]]; then
    stale_caps="$(yq -r --arg cutoff "$cutoff" '.capabilities[]? | select(.lastValidated // "9999-01-01T00:00:00Z" < $cutoff) | "- " + .id + " (last validated: " + (.lastValidated // "never") + ")"' "$LEDGER_FILE" 2>/dev/null | head -10 || true)"
  fi
fi
[[ -z "$stale_caps" ]] && stale_caps="- (no stale capabilities detected, or capability ledger missing)"

# Total event count (signal volume)
event_count=0
[[ -f "$EVENTS_FILE" ]] && event_count="$(wc -l < "$EVENTS_FILE" 2>/dev/null || echo 0)"

# Write the proposal
cat > "$OUT_FILE" <<EOF
# IMP-$(printf "%03d" "$next_num") — $SLUG

**Type:** Framework improvement proposal (auto-generated by \`bubbles.retro target: framework\`)
**Date:** $(date -u +%FT%TZ)
**Auto-mutation:** NONE. This is a proposal only. Human reviews and decides whether to spec the change.

## Signal Volume

- Framework events analyzed: $event_count line(s) in \`.specify/runtime/framework-events.jsonl\`

## Diagnosis

### Top failing gates

$top_failed_gates

### Stalled / non-completed workflow modes

$stalled_modes

### Stale capabilities (last validated > 90 days ago)

$stale_caps

## Recommended next step

If any of the above signals warrant a framework change:

1. Open a new spec under \`specs/NNN-<slug>/\` describing the proposed change.
2. Use \`/bubbles.workflow full-delivery\` to plan + implement + validate the change.
3. Reference this IMP file in the spec's \`design.md\` Diagnosis section.

If the signals are healthy and no change is warranted, mark this proposal as \`status: noop\` and archive.

## Provenance

- Generated by: \`bubbles/scripts/retro-framework-health.sh\`
- Input sources: \`.specify/runtime/framework-events.jsonl\`, \`.specify/runtime/workflow-runs.json\`, \`bubbles/capability-ledger.yaml\`
- Mutation: ZERO framework files modified by this script.

EOF

echo "[retro-framework-health] Wrote $OUT_FILE"
exit 0
