#!/usr/bin/env bash
#
# validate-cache.sh — content-addressed result cache for hermetic selftests
# (IMP-027 / SCOPE-7).
#
# WHY THIS EXISTS
# ---------------
# framework-validate.sh --tier=core took 260 seconds to run 16 of 209 checks.
# The full tier is what pre-push runs. A ~25-minute serial pre-push is the
# single strongest practical incentive toward the bypass behaviour the whole
# framework exists to prevent, so the wall clock is a governance problem, not
# an ergonomics one.
#
# WHAT IS SAFE TO REUSE
# ---------------------
# ONLY a check whose DECLARED INPUT CLOSURE is complete. The closure comes from
# `bubbles/registry/validation-checks.yaml`, which is GENERATED by tracing real
# `source`/`bash` references and literal path tokens. Reuse is permitted when
# every declared input hashes to what it hashed when the verdict was recorded.
#
# The previous key was a basename pair and it was a guess; see validate_cache_key
# below for what that guess cost.
#
# LIVE GUARDS ARE NEVER REUSED. They read the working tree, which is exactly
# what changes between runs. Reusing one would mean reporting a verdict about a
# tree that was never inspected — the same "reported success for a check that
# never ran" failure this proposal's SEC-2 work removed. Those checks carry
# `closureComplete: false` and therefore never receive a key.
#
# The entry also records the framework version, so a version bump invalidates
# every entry rather than silently carrying verdicts across releases.
#
# Usage:
#   validate_cache_key <script-path>          -> prints a key, or empty if unsafe
#   validate_cache_get <key>                  -> exit 0 if a PASS is cached
#   validate_cache_put <key> <exit-code>      -> record a verdict (pass only)
#   validate_cache_receipt <key>              -> the receipt id a REUSED result cites
#   validate_cache_prune                      -> drop entries older than 30 days

set -uo pipefail

: "${BUBBLES_VALIDATE_CACHE_DIR:=${XDG_CACHE_HOME:-$HOME/.cache}/bubbles/validate}"

# The closure consumer owns the reuse key (IMP-047 S-E). Sourcing it here keeps
# every caller of validate_cache_key on the same key derivation; absence simply
# means no key is ever produced, which forbids reuse rather than falling back to
# the retired basename guess.
_VALIDATE_CACHE_DIR_SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "$_VALIDATE_CACHE_DIR_SELF/validation-closure.sh" ]]; then
  # shellcheck source=bubbles/scripts/validation-closure.sh
  source "$_VALIDATE_CACHE_DIR_SELF/validation-closure.sh"
fi

# validate_cache_enabled — the cache is opt-OUT, but never active in CI, where a
# cold, complete run is the entire point.
validate_cache_enabled() {
  [[ "${BUBBLES_VALIDATE_CACHE:-1}" == "1" ]] || return 1
  [[ -z "${CI:-}" ]] || return 1
  command -v sha256sum >/dev/null 2>&1 || return 1
  return 0
}

# validate_cache_key <script-path> [framework-version]
#
# IMP-047 S-E. The key used to be a BASENAME PAIR ALONE: sha256(selftest) +
# sha256(the `X.sh` whose name matched `X-selftest.sh`). That pair is a guess
# about dependencies, and on its own it was wrong for 100 checks that
# `source guard-lib.sh` and 97 that read `bubbles/registry/gates.yaml`. Editing
# either changed no basename, so the cache kept serving a PASS about inputs it
# had never re-examined — the same staleness class the evidence guards catch.
#
# TWO BRANCHES, ONE RULE: NEVER PRODUCE A KEY FOR AN INPUT SET NOBODY KNOWS.
#
#   IN-TREE checks — every check framework-validate.sh actually schedules — are
#   keyed on the DECLARED INPUT CLOSURE from
#   `bubbles/registry/validation-checks.yaml`, DERIVED by tracing real
#   references. It covers every transitively reachable script, every registry
#   and schema file those scripts name, the framework version, the platform, and
#   the version string of every external command in the closure. A check the map
#   does not carry, or one it carries as `closureComplete: false`, gets NO KEY
#   and therefore always executes: not knowing the inputs is not the same as
#   knowing they did not change, and only one of those permits reuse.
#
#   OUT-OF-TREE fixtures — a script under `mktemp`, which is what a hermetic
#   selftest builds — have no entry in the framework's closure map and never
#   will, because the map only describes this repository. The closure map is not
#   silent about them by accident, so falling back to it would be meaningless.
#   Their key is content-addressed over the fixture and the subject it names,
#   which is the whole of their input set. This branch is unreachable from
#   framework-validate.sh, which only ever passes in-tree paths.
#
# A LIVE GUARD IS REFUSED IN BOTH BRANCHES. It reads the working tree, so a
# reused verdict would describe a tree that was never inspected.
validate_cache_key() {
  local script="$1"
  local version="${2:-unknown}"

  [[ -f "$script" ]] || return 1
  case "$(basename "$script")" in
    *-selftest.sh) ;;
    *) return 1 ;;
  esac

  local root="${VCLOSURE_REPO_ROOT:-}"
  if [[ -n "$root" && "$script" == "$root/"* ]]; then
    _validate_cache_key_closure "${script#"$root"/}" "$version"
    return
  fi
  _validate_cache_key_fixture "$script" "$version"
}

# The in-tree key: the declared input closure, or nothing at all.
_validate_cache_key_closure() {
  local rel="$1" version="$2"

  declare -F vclosure_load >/dev/null 2>&1 || return 1
  if [[ -z "${VCLOSURE_LOADED:-}" ]]; then
    vclosure_load >/dev/null 2>&1 || return 1
  fi

  local id
  id="$(vclosure_id_for_script "$rel")"
  [[ -n "$id" ]] || return 1
  vclosure_reusable "$id" || return 1

  local digest
  digest="$(vclosure_digest "$id" "$version")" || return 1
  [[ -n "$digest" ]] || return 1
  printf '%s-%s' "$version" "$digest"
}

# The out-of-tree fixture key. The framework closure map describes this
# repository only, so for a script outside it the fixture plus the subject its
# name declares IS the enumerable input set, and the version and platform join
# it for the same reason they join the closure digest.
_validate_cache_key_fixture() {
  local script="$1" version="$2"
  local subject="${script%-selftest.sh}.sh"
  local self_digest subject_digest digest

  self_digest="$(sha256sum <"$script" 2>/dev/null | cut -d' ' -f1)" || return 1
  [[ -n "$self_digest" ]] || return 1
  subject_digest="absent"
  if [[ -f "$subject" ]]; then
    subject_digest="$(sha256sum <"$subject" 2>/dev/null | cut -d' ' -f1)" || return 1
  fi
  digest="$(
    printf 'fixture-v1\nversion=%s\nplatform=%s\nself=%s\nsubject=%s\n' \
      "$version" "$(uname -s 2>/dev/null || echo unknown)" "$self_digest" "$subject_digest" |
      sha256sum 2>/dev/null | cut -d' ' -f1
  )" || return 1
  [[ -n "$digest" ]] || return 1
  printf '%s-%s' "$version" "$digest"
}

# The receipt a REUSED result cites. A reuse claim that cannot name the record it
# reused is indistinguishable from an unverified assertion.
validate_cache_receipt() {
  local key="$1"
  [[ -n "$key" ]] || return 1
  printf 'vcr-%s' "${key##*-}"
}

validate_cache_get() {
  local key="$1"
  validate_cache_enabled || return 1
  [[ -n "$key" ]] || return 1
  [[ -f "$BUBBLES_VALIDATE_CACHE_DIR/$key" ]] || return 1
  return 0
}

# validate_cache_put <key> <exit-code>
#
# Only PASSES are cached. Caching a failure would let a fixed script keep
# reporting its old failure until something invalidated the entry, and a stale
# red is just as dishonest as a stale green.
validate_cache_put() {
  local key="$1" code="$2"
  validate_cache_enabled || return 0
  [[ -n "$key" ]] || return 0
  [[ "$code" -eq 0 ]] || return 0
  mkdir -p "$BUBBLES_VALIDATE_CACHE_DIR" 2>/dev/null || return 0
  : >"$BUBBLES_VALIDATE_CACHE_DIR/$key" 2>/dev/null || return 0
  return 0
}

validate_cache_prune() {
  [[ -d "$BUBBLES_VALIDATE_CACHE_DIR" ]] || return 0
  find "$BUBBLES_VALIDATE_CACHE_DIR" -type f -mtime +30 -delete 2>/dev/null || true
}

validate_cache_clear() {
  [[ -d "$BUBBLES_VALIDATE_CACHE_DIR" ]] || return 0
  rm -rf "${BUBBLES_VALIDATE_CACHE_DIR:?}"/* 2>/dev/null || true
}
