-- 058_web_registration_invites.sql
-- Spec 093 — admin-generated, single-use, DB-backed registration invites.
--
-- Augments spec 091's invite-gated web self-registration. A logged-in operator
-- GENERATES a single-use invite from the web UI; the PLAINTEXT token is shown
-- exactly once and is NEVER persisted — only its SHA-256 (hex) lives here. A
-- new person registers once at /register with the plaintext; on success the
-- account is created and the invite is atomically marked used (single-use,
-- guarded UPDATE — same TOCTOU posture as 032_photo_reveal_tokens). The static
-- WEB_REGISTRATION_INVITE_TOKEN is unchanged and kept as bootstrap.
--
-- id PK convention follows 019_expense_tracking.sql (TEXT + gen_random_uuid()::text)
-- so the {id} revoke route param and the List view-model are plain strings.

CREATE TABLE IF NOT EXISTS web_registration_invites (
    id          TEXT        PRIMARY KEY DEFAULT gen_random_uuid()::text,
    token_hash  TEXT        NOT NULL UNIQUE,
    label       TEXT,
    created_by  TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at  TIMESTAMPTZ,
    used_at     TIMESTAMPTZ,
    used_by     TEXT,
    revoked_at  TIMESTAMPTZ
);

COMMENT ON TABLE  web_registration_invites IS
    'Spec 093 — single-use, hashed-at-rest registration invites generated by a logged-in operator. Holds only the SHA-256 (hex) of the plaintext token; the plaintext is shown once at generation and never stored. Augments (does not replace) the static WEB_REGISTRATION_INVITE_TOKEN bootstrap gate.';
COMMENT ON COLUMN web_registration_invites.token_hash IS
    'Lowercase hex SHA-256 of the plaintext invite token (incl. the inv_ prefix). The plaintext is NEVER stored. Lookup + single-use consume is by this hash. UNIQUE so two live invites cannot collide.';
COMMENT ON COLUMN web_registration_invites.label IS
    'Optional operator-facing note (e.g. "for the new analyst"). Metadata only; safe to display in the list.';
COMMENT ON COLUMN web_registration_invites.created_by IS
    'Display identity of the web session that generated the invite (auth.Session.UserID when present, else "operator"). Metadata only — NOT an authorization key.';
COMMENT ON COLUMN web_registration_invites.expires_at IS
    'Optional TTL boundary. NULL = never expires. The consume + gate guards check (expires_at IS NULL OR expires_at > now()). v1 default at generation is now()+7 days.';
COMMENT ON COLUMN web_registration_invites.used_at IS
    'Set atomically (same tx as the account INSERT) when the invite is consumed by a successful /register. NULL while outstanding.';
COMMENT ON COLUMN web_registration_invites.used_by IS
    'Username that consumed the invite (the new account). NULL while outstanding.';
COMMENT ON COLUMN web_registration_invites.revoked_at IS
    'Set when the operator revokes an OUTSTANDING invite. A revoked invite can never register.';

-- The UNIQUE constraint on token_hash already provides the by-hash lookup index.
-- A partial index for the "live" predicate is unnecessary at operator scale.

-- Rollback (manual):
-- DROP TABLE IF EXISTS web_registration_invites;
