// Command web-assistant-codegen regenerates the committed
// web/PWA assistant-turn v1 artifacts (spec 073 Scope 1c) from the
// canonical wire-schema at internal/assistant/schema/assistant_turn_v1.json.
//
// Invocation:
//
//	go run ./cmd/web-assistant-codegen
//	  [--schema internal/assistant/schema/assistant_turn_v1.json]
//	  [--out web/pwa/generated]
//	  [--check]
//
// --check exits non-zero if the on-disk artifacts do not match the
// freshly-generated bytes (used by the codegen-drift test and the
// build pipeline).
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/smackerel/smackerel/internal/assistant/schema/webcodegen"
)

func main() {
	schemaPath := flag.String("schema", webcodegen.SchemaFile, "canonical wire-schema JSON path")
	outDir := flag.String("out", webcodegen.GeneratedDir, "output directory for generated artifacts")
	check := flag.Bool("check", false, "fail with a diff summary if on-disk artifacts differ from regenerated output")
	flag.Parse()

	schemaBytes, err := os.ReadFile(*schemaPath)
	if err != nil {
		fail("read schema %s: %v", *schemaPath, err)
	}
	artifacts, err := webcodegen.Generate(schemaBytes)
	if err != nil {
		fail("generate: %v", err)
	}

	names := make([]string, 0, len(artifacts))
	for name := range artifacts {
		names = append(names, name)
	}
	sort.Strings(names)

	if *check {
		var drift []string
		for _, name := range names {
			path := filepath.Join(*outDir, name)
			onDisk, err := os.ReadFile(path)
			if err != nil {
				drift = append(drift, fmt.Sprintf("%s: %v", path, err))
				continue
			}
			if !bytes.Equal(onDisk, artifacts[name]) {
				drift = append(drift, fmt.Sprintf("%s: differs from regenerated bytes (%d on-disk vs %d generated)", path, len(onDisk), len(artifacts[name])))
			}
		}
		if len(drift) > 0 {
			fmt.Fprintln(os.Stderr, "web-assistant-codegen: drift detected:")
			for _, line := range drift {
				fmt.Fprintln(os.Stderr, "  - "+line)
			}
			fmt.Fprintln(os.Stderr, "Regenerate with: go run ./cmd/web-assistant-codegen")
			os.Exit(2)
		}
		fmt.Println("web-assistant-codegen: on-disk artifacts match canonical schema")
		return
	}

	if err := os.MkdirAll(*outDir, 0o755); err != nil {
		fail("mkdir %s: %v", *outDir, err)
	}
	for _, name := range names {
		path := filepath.Join(*outDir, name)
		if err := os.WriteFile(path, artifacts[name], 0o644); err != nil {
			fail("write %s: %v", path, err)
		}
		fmt.Println("wrote " + path)
	}
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "web-assistant-codegen: "+format+"\n", args...)
	os.Exit(1)
}
